name: "elt"
version: "1.0.0"
config-version: 2

profile: "elt"

model-paths: ["models"]
macro-paths: ["macros"]

models:
  elt:
    staging:
      +schema: staging
      materialized: table
    marts:
      +schema: marts
      +materialized: table